var allArticles = [
    {
        title:'SVG相关学习(一)SVG基础',
        tags:['SVG','动画'],
        target:'https://github.com/liubin915249126/HTML-CSS-SVG/tree/master/SVG#svg-%E7%9B%B8%E5%85%B3%E5%AD%A6%E4%B9%A0',
        img:{src:'https://github.com/liubin915249126/HTML-CSS-SVG/raw/master/SVG/image/SVGArcs_Flags.png',alt:'SVGArcs_Flags'},
        description:'主要包括SVG基础知识，基本图形，渐变，还有path路径相关'
    },
    {
        title:'连接两个div的直线，拖动时保持连线',
        tags:['SVG','动画'],
        target:'https://github.com/liubin915249126/javascript/tree/master/SVG#%E7%94%A8svg%E8%BF%9E%E6%8E%A5%E4%B8%A4%E4%B8%AAdiv%E7%9A%84%E7%9B%B4%E7%BA%BF%E6%8B%96%E5%8A%A8%E5%AE%9E%E6%97%B6%E6%94%B9%E5%8F%98%E4%BD%8D%E7%BD%AE',
        img:{src:'https://github.com/liubin915249126/javascript/raw/master/SVG/image/svgDrag.gif',alt:'效果图'},
        description:'连接两个div带箭头的虚线，拖动div时保持线条实时改变位置保持始终连接'
    },
    {
        title:'原生js实现视差滚动效果（类似D3官网的效果），兼容IE',
        tags:['javascript','动画','Parallax'],
        target:'https://github.com/liubin915249126/javascript/tree/master/Parallax#js%E8%A7%86%E5%B7%AE%E6%95%88%E6%9E%9C',
        img:{src:'https://github.com/liubin915249126/javascript/raw/master/Parallax/img/parallax.gif',alt:'效果图'},
        description:'鼠标在图片上上下左右滑动时,让图片整体转动,转动方向与鼠标移动的方向相同,从而实现视差效果'
    },
    {
        title:'jquery组织架构图插件',
        tags:['javascript','动画','jquery','jquery插件','orgnization'],
        target:'https://github.com/liubin915249126/javascript/tree/master/lencharts#jquery%E6%8F%92%E4%BB%B6',
        img:{src:'https://github.com/liubin915249126/javascript/raw/master/lencharts/image/lenchart.gif',alt:'效果图'},
        description:'使用递归的方式深层遍历数据,架构图第二层为横向结构,从第三层开始为竖向结构,解决了横向太长的问题。点击加减号按钮可以显示与隐藏当前节点的子节点。'
    }
    
]